### ISSUE TITLE
add home page

### ISSUE THREAD

**Issue by oliviervd** [oliviervd/MODELS-FROM-THE-PAST-FOR-THE-FUTURE#68]
* [ ] link to glossary #3 
* [ ] graphic identity (creative coding grid, something with fonts?) #69 
* [ ] modals for models #62
* [ ] visual identity for empty models (add reusable element) #72 
* [x] curatorial statement #70
